---

# Load a variable file based on the OS type, or a default if not found.
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"

- name: Ensure the data directory exists
  file:
    path: "{{postgresql_data_directory}}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700

- name: Ensure the conf directory exists
  sudo: yes
  file:
    path: "{{postgresql_conf_directory}}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
    
- name: configure pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{postgresql_conf_directory}}/pg_hba.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  sudo: yes
  notify: 
   - restart_postgres_apt
   - restart_postgers_darwin

- name: configure postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{postgresql_conf_directory}}/postgresql.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  sudo: yes
  notify: 
   - restart_postgres_apt
   - restart_postgers_darwin

- name: Start services at login
  file: src=/usr/local/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist state=link force=yes
  when: ansible_os_family == "Darwin"
     
- name: Setup launch agents for services
  command: launchctl load {{ home }}/Library/LaunchAgents/homebrew.mxcl.postresql.plist
  when: ansible_os_family == "Darwin"
  
