---

 - include: "../../pkg_mgr_apt/tasks/install_package.yml package_name=postgresql-{{ postgresql_version }}"
   when: ansible_pkg_mgr == "apt"

 - include: "../../pkg_mgr_apt/tasks/install_package.yml package_name=postgresql-contrib-{{ postgresql_version }}"
   when: ansible_pkg_mgr == "apt"
   
 - include: "../../pkg_mgr_apt/tasks/install_package.yml package_name=pgadmin3"
   when: ansible_pkg_mgr == "apt"

 - homebrew: update_homebrew=yes
   when: ansible_os_family == "Darwin"

 - include: "../../pkg_mgr_homebrew/tasks/install_package.yml package_name=postgresql"
   when: ansible_os_family == "Darwin"
   
 - include: "../../pkg_mgr_homebrew/tasks/install_cask_package.yml package_name=pgadmin3"
   when: ansible_os_family == "Darwin"
