---

 - include: ../../pkg_mgr_apt/tasks/install_package.yml package_names=['postgresql']
   when: ansible_pkg_mgr == "apt"

 - include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_names=['postgresql']
   when: ansible_os_family == "Darwin"
  
# - name: Copy valid pg_hba.conf
#   template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf

# - name: postgresql.conf
#   template: src=postgresql.conf.j2 dest=/etc/postgresql/9.3/main/postgresql.conf

# - name: Restart PostgreSQL
#   command: service postgresql restart

 - name: create the postgresql user for application
   postgresql_user: name=postgres
   sudo: yes
#superuser? pw=user?

# - name: create the postgresql database for ld
#   postgresql_db: name=app_{{app_name}} owner=deploy state=present
#   sudo: yes
#   sudo_user: postgres
