---

- name: Download intellij
  get_url: url={{intellij_url}} dest={{intellij_tmp}}

- name: Ensure installation directory
  file:
    state=directory
    mode=0755
    dest={{intellij_install_dir}}
  become: true

- name: Unarchive intellij
  unarchive:
    copy=no
    src={{intellij_tmp}}
    dest={{intellij_install_dir}}
  become: true
