---

 - hosts: all
   tasks:
     - group_by: key=os_{{ ansible_os_family }}

 - hosts: all
   gather_facts: false
   tasks:
     - group_by: key=pkg_mgr_{{ ansible_pkg_mgr }}

 - hosts: all
   gather_facts: false
   tasks:
     - group_by: key=user_{{ ansible_user_id }}

 - hosts: all
   gather_facts: false
 - include: workstation.yml
