---

 - hosts: all
   tasks:
     - group_by: key=os_{{ ansible_os_family }}


 - hosts: all
   tasks:
     - group_by: key=pkg_mgr_{{ ansible_pkg_mgr }}

 - hosts: os_Darwin
   gather_facts: false
   roles:
     - pkg_mgr_homebrew

 - hosts: pkg_mgr_apt
   gather_facts: false
   roles:
     - pkg_mgr_apt

 - hosts: all
 - include: workstation.yml
 

 

