---
- hosts: all

  roles:

# system
    - sshd

# text editors
    - emacs
    - vim
    - sublime-text

# languages
    - java7
    - nodejs
    - python

# development tools
    - git
    - ant
    - gawk
    - grunt-cli
    - p7zip
    - tmux
    - wget
    - zsh
    - zsh-completions
    - virtualbox
    - vagrant
    - virtualenv

# databases
    - postgresql
    - mongodb

# browsers
    - google-chrome
    - firefox

# livedesign
    - python-psycopg2

# applications
    - evernote
    - google-drive
    - hipchat
    - sourcetree
    - calibre
    - gimp
    - reggy
    - skitch
    - skype
    - graphviz
    - vlc
    - the-unarchiver

    - users
