---
- hosts: all

  roles:

# text editors
    - emacs
    - vim

# languages
    - java7
    - nodejs
    - python

# development tools
    - ant
    - gawk
    - p7zip
    - tmux
    - wget
    - zsh
    - virtualbox
    - virtualenv

# databases
    - postgresql

# browsers
    - google-chrome
    - firefox

# livedesign
    - python-psycopg2

# applications
#    - evernote
#    - googledrive
#    - hipchat
#    - sourcetree
#    - calibre
#    - cord
#    - gimp
#    - reggy
#    - shiftit
#    - skitch
#    - skype
#    - graphviz
#    - vlc


    
