---

- name: Add ppa for sublime-text3
  apt_repository:
  become: true
  args:
    state: present
    repo: "ppa:webupd8team/sublime-text-3"
    update_cache: yes

- name: Install sublime-text with apt
  apt: name=sublime-text3 state=latest
  become: true
