---

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install with apt
  sudo: yes
  action: "{{ packager }} name={{ item }} state=present"
  with_items: items
