---

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=zsh
  when: ansible_pkg_mgr == "apt"

- include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_name=zsh
  when: ansible_os_family == "Darwin"

- name: make zsh default
  shell:  chsh -s /bin/zsh 
  
