---

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=zsh
  when: ansible_pkg_mgr == "apt"

- include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_name=zsh
  when: ansible_os_family == "Darwin"

- name: Set zsh as default shell
  user: name={{ ansible_user_id }} shell=/bin/zsh


- name: Check oh-my-zsh is installed
  stat: path=~/.oh-my-zsh
  register: oh_my_zsh_installed

- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  when: oh_my_zsh_installed.stat.exists == false
  
