---


- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=git
  when: ansible_pkg_mgr == "apt"

- include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_name=git
  when: ansible_os_family == "Darwin"

- name: global config
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    backup: yes

- name: global gitignore
  template:
    src: gitignore_global
    dest: ~/.gitignore_global
    backup: yes
