---

- include: ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- include: osx.yml
  when: ansible_os_family == "Darwin"

- name: global gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    backup: yes

- name: global gitignore
  template:
    src: gitignore_global
    dest: ~/.gitignore_global
    backup: yes
