---

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- name: global gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    backup: yes

- name: global gitignore
  template:
    src: gitignore_global
    dest: ~/.gitignore_global
    backup: yes

- name: global git commit message template
  template:
    src: gitmessage.j2
    dest: ~/.gitmessage
    backup: yes
