---
- name: Clone prelude
  git: >
    repo=git://github.com/bbatsov/prelude.git
    accept_hostkey=yes
    dest=~/.emacs.d
    force=no

- name: prelude modules
  copy: src=conf/ dest=~/.emacs.d backup=yes

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=emacs
  when: ansible_pkg_mgr == "apt"
  notify: Install emacs packages

- include: ../../pkg_mgr_homebrew/tasks/install_package.yml package_name=emacs install_options=cocoa
  when: ansible_os_family == "Darwin"
  notify: Install emacs packages

# TODO this should not be be need with linkapps handler
- name: link
  file: src=/usr/local/Cellar/emacs/24.4/Emacs.app dest=/Applications/Emacs.app state=link
  when: ansible_os_family == "Darwin"
  
# TODO this does not work here, move to separate handler file?
- name: Install emacs packages
  shell: emacs  --batch --eval t
