---

- name: Install emacs with homebrew cask
  homebrew_cask: name=emacs state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  become: true
  notify: Install emacs packages
