---

- name: Add ppa
  apt_repository:
  become: true
  args:
    state: present
    repo: 'ppa:kelleyk/emacs'
    update_cache: yes

- name: Install emacs26 with apt
  apt: name=emacs26 state=absent
  become: true
  notify: Install emacs packages
