---

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_names=[ 'virtualbox-ose-dkms', 'virtualbox-ose' ]
  when: ansible_pkg_mgr == "apt" and ansible_distribution_release == "precise"
  
  name: add virtualbox repo
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian trusty contrib' state=present
  when: ansible_pkg_mgr == 'apt' and ansible_distribution_release == 'trusty'

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_names=[ 'dkms', 'virtualbox-4.3' ]
  when: ansible_pkg_mgr == 'apt' and ansible_distribution_release == 'trusty'

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml
  when: ansible_os_family == "Darwin"

