---

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=virtualbox-ose-dkms
  when: ansible_pkg_mgr == "apt" and ansible_distribution_release == "precise"

# TODO need install for trusty 64

- name: add repo key
  sudo: yes
  apt_key: state=present
           url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_apt/tasks/install_package.yml package_name=virtualbox-ose
  when: ansible_pkg_mgr == "apt" 

- include: ../../pkg_mgr_homebrew/tasks/install_cask_package.yml
  when: ansible_os_family == "Darwin"
