---

- name: add VirtualBox repo signing key
  apt_key:
    id: A2F683C52980AECF
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present
  become: true

- name: add VirtualBox repo
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"
    state: present
    update_cache: true
  become: true

- name: Install dkms with apt
  apt:
    name: dkms
    state: latest
  become: true

- name: Install virtualbox with apt
  apt:
    name: virtualbox-5.1
    state: latest
  become: true
