---

- name: "OS X Preferences"
  command: defaults write {{item.domain}} {{item.key}} {{item.value}}
  with_items: osx.prefs
  when: ansible_os_family == "Darwin"
  tags:
    - test

- name: restart Finder and Dock
  command: killAll {{ item }}
  with_items:
    - Finder
    - Dock
