---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Homebrew for Mac OS X
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: GenericUNIX
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - system
    - packaging
