---

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# expect sshd already installed on macox

- name: Ensure ~./sshd directory exists
  file:
    path: ~/.ssh
    state: directory

- openssh_keypair:
    path: ~/.ssh/id_rsa
